### PR TITLE
feat: disable jsdoc

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by popomore** [comment]
感觉很多人都会写错，不需要太严格

**Comment by whxaxes** [comment]
貌似 eslint-config-egg 里也是开启了，那统一关掉？

**Comment by popomore** [comment]
嗯，也关掉好了

**Comment by popomore** [comment]
其实 ts 有类型就够了，不用 jsdoc

**Comment by popomore** [comment]
+ tslint-config-egg@1.0.0-alpha.3

**Pull request merged**
