### PR TITLE
Feature 1.0

### PR DESCRIPTION
**Pull request by whxaxes**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

tslint config for egg

### CODE REVIEW

**Comment by whxaxes** [comment]
eslint 的规则通过 https://github.com/buzinas/tslint-eslint-rules 实现，不过仅支持一部分。

**Comment by popomore** [comment]
先发个 alpha 版？

**Comment by whxaxes** [comment]
1.0.0-alpha

**Comment by whxaxes** [comment]
好，之后就按这种格式

**Pull request merged**
