### PR TITLE
refactor: always add trailing comma when multiline

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by whxaxes** [comment]
本来是 always 的，不过考虑到跟 eslint-config-egg 保持一致，所以改成 function 就不用了

**Comment by popomore** [comment]
eslint 现在也可以改成 always 了，原来是 Node 不支持

**Comment by whxaxes** [comment]
OK，那就都改一下吧，保持一致好些

**Comment by popomore** [comment]
eslint 改的话要 drop node6

**Comment by popomore** [comment]
+ tslint-config-egg@1.0.0-alpha.3

**Pull request merged**
